"""phase6 playbook automation

Revision ID: 2387e5fbde4b
Revises: 4a365bafd615
Create Date: 2026-08-03 19:38:35.097671

This migration was generated with --autogenerate against your real repo
(cloned directly from the anaskhan2703-patch-1 branch) and verified
end-to-end in a live Postgres 16 instance, including upgrade -> downgrade
-> upgrade, with a pre-existing playbooks row present (to exercise the
NOT NULL backfill below) and a pre-existing alerts row (to confirm the new
FKs attach cleanly).

Before running `alembic upgrade head`:
  - Confirm your current head is 4a365bafd615 (`alembic heads`). If Phase 5
    added a migration in your real repo that this branch doesn't reflect,
    update down_revision below to match.
  - This alters playbooks.trigger_type to NOT NULL. The backfill step
    (UPDATE ... SET trigger_type = 'automatic' WHERE trigger_type IS NULL)
    runs first, so any existing rows with a null trigger_type won't break
    the alter — but double check that "automatic" is the right default for
    any playbooks you already created, since a null trigger_type before
    this migration wasn't previously being evaluated automatically at all.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2387e5fbde4b'
down_revision: Union[str, Sequence[str], None] = '4a365bafd615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playbook_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('playbook_id', sa.UUID(), nullable=True),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('executed_by', sa.UUID(), nullable=True),
    sa.Column('trigger_source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('triggered_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actions_taken', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbook_executions_alert_id'), 'playbook_executions', ['alert_id'], unique=False)
    op.create_index(op.f('ix_playbook_executions_executed_by'), 'playbook_executions', ['executed_by'], unique=False)
    op.create_index(op.f('ix_playbook_executions_playbook_id'), 'playbook_executions', ['playbook_id'], unique=False)
    op.add_column('playbooks', sa.Column('trigger_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # Backfill before tightening to NOT NULL — any playbook created before
    # this migration existed had no trigger_type at all.
    op.execute("UPDATE playbooks SET trigger_type = 'automatic' WHERE trigger_type IS NULL")

    op.alter_column('playbooks', 'trigger_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               server_default='automatic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playbooks', 'trigger_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('playbooks', 'trigger_conditions')
    op.drop_index(op.f('ix_playbook_executions_playbook_id'), table_name='playbook_executions')
    op.drop_index(op.f('ix_playbook_executions_executed_by'), table_name='playbook_executions')
    op.drop_index(op.f('ix_playbook_executions_alert_id'), table_name='playbook_executions')
    op.drop_table('playbook_executions')
    # ### end Alembic commands ###
